"updates":
- "directory": "/"
  "open-pull-requests-limit": 6
  "package-ecosystem": "cargo"
  "schedule":
    "interval": "daily"
    "time": "08:00"
    "timezone": "UTC"
- "directories":
  - "/"
  - "/clients/js"
  - "/clients/js-legacy"
  "open-pull-requests-limit": 6
  "package-ecosystem": "npm"
  "schedule":
    "interval": "daily"
    "time": "09:00"
    "timezone": "UTC"
"version": 2
